### ISSUE TITLE
Use of Accordion with other Content Elements

### ISSUE THREAD

**Issue by bh-teufels** [buepro/typo3-container_elements#4]
is it possible to use Accordions with other Content-Elements than Header or Text?
for my example i want to put different news (georgringer) in different Accordion-"Tabs"

is it for example possible to place container inside accordion? Would be great to build accordion with 50:50 content or other Content Types

**Comment by buepro** [comment]
Yes this works fine, any content type can be added. You might explore the possibilities with the [pizpalue_distribution](https://extensions.typo3.org/extension/pizpalue_distribution/). Some container examples can be found on the [demo page](https://pizpalue.buechler.pro/das-plus/strukturelemente/container).

**Comment by bh-teufels** [comment]
So do i need pizpalue_distribution that this feature is working?

**Comment by buepro** [comment]
No, the pizpalue_distribution provides just an easy way to check it out (just setup a TYPO3 instance, go to the extension manager and install the distribution).

**Comment by bh-teufels** [comment]
Okay, because i have the Problem that if i put for example 
news plugin - List selected News - 1 Selected
inside the Accordion-Container it get not rendered in the frontend.

Same if i put a 50:50 Container (With Text CE inside left & richt Col) inside the Accordion Container
-> 50:50 Container with Text not rendered

**Comment by buepro** [comment]
Since it works using the [bootstrap_package](https://extensions.typo3.org/extension/bootstrap_package) the problem might be related to the page setup. You might checkout the setup from the bootstrap_package to solve the issue. The following files might be of interest:
- [setup.typoscript](https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.typoscript)
- [ContentElement.typoscript](https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/ContentElement/Helper/ContentElement.typoscript) 
- [DynamicContent.typoscript](https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/ContentElement/Helper/DynamicContent.typoscript)
