### ISSUE TITLE
Remove access to "classes" for User Groups

### ISSUE THREAD

**Issue by bh-teufels** [buepro/typo3-container_elements#5]
is it possible to remove access to

- containerClass
- containerAttribute
- sectionClass

- row.class
- columns.<n>.class

- ...

for Backend User Groups?

id don't want my editors to change that

**Comment by buepro** [comment]
Since those fields are provided through a flexform (in field `pi_flexform`) the standard mechanisms for field access control aren't available. But the flexform configuration can be adapted by TSconfig. User group TSconfig examples:

- Disable the field `row.class` in sheet `sCustom`:
`page.TCEFORM.tt_content.pi_flexform.ce_columns2.sCustom.row\.class.disabled = 1`
- Disable sheet `sCustom`:
`page.TCEFORM.tt_content.pi_flexform.ce_columns2.sCustom.disabled = 1`

**Comment by bh-teufels** [comment]
thank you very much

**Comment by bh-teufels** [comment]
thank you very much
